# Generated by Django 4.0.1 on 2022-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('genre', models.CharField(choices=[('Detective', 'Detective'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Anime', 'Anime')], max_length=100)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
