# Generated by Django 4.0.1 on 2022-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_genre_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('Detective', 'Detective'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Anime', 'Anime')], max_length=100, null=True),
        ),
    ]
