# Generated by Django 4.0.1 on 2022-01-23 14:29

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.TextField()),
                ('date_of_birth', models.IntegerField()),
                ('activity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation_text', models.TextField()),
                ('expert', models.ForeignKey(on_delete=book.models.Expert, related_name='expert_info', to='book.genre')),
            ],
        ),
    ]
