# Generated by Django 4.0.1 on 2022-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_expert_expertrecomendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='date_of_birth',
            field=models.TextField(),
        ),
    ]
