# Generated by Django 4.0.1 on 2022-01-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_expert_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrecomendation',
            name='courses',
            field=models.ManyToManyField(related_name='info_exp', to='book.Expert'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expertrecomendation',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_info', to='book.genre'),
        ),
        migrations.AlterField(
            model_name='expertrecomendation',
            name='recomendation_text',
            field=models.TextField(null=True),
        ),
    ]
